app:
  image: ibmcom/kitura-ubuntu
  ports:
    - "8090:8090"
  volumes:
    - .:/root/hello-world
  command: bash -c "make clean -C hello-world && make -C hello-world && hello-world/.build/debug/hello-world"
