app:
  image: ibmcom/swift-ubuntu
  ports:
    - "8090:8090"
  volumes:
    - .:/root/hello-world
  command: bash -c "cd /root/hello-world && swift build --clean && swift build -v && /root/hello-world/.build/debug/hello-world"
